create table city (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(80) not null,
	state_id int not null
);

alter table city add constraint fk_city_state
foreign key (state_id) references state (id);