create table group_security (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(60) not null
) ;

create table group_security_permission (
	group_security_id integer not null,
	permission_id integer not null,
	primary key (group_security_id, permission_id)
) ;

create table permission (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	description varchar(60) not null,
	name varchar(100) not null
) ;

alter table group_security_permission add constraint fk_group_security_permission_permission
foreign key (permission_id) references permission (id);

alter table group_security_permission add constraint fk_group_security_permission_group_security
foreign key (group_security_id) references group_security (id);