create table product (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	restaurant_id integer not null,
	name varchar(80) not null,
	description text not null,
	price decimal(10,2) not null,
	active boolean not null
) ;

alter table product add constraint fk_product_restaurant
foreign key (restaurant_id) references restaurant (id);
