create table users (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(80) not null,
	email varchar(255) not null,
	password varchar(255) not null,
	created_at TIMESTAMP not null
);

create table users_group (
	users_id integer not null,
	group_id integer not null,
	primary key (users_id, group_id)
);

alter table users_group add constraint fk_users_group_group
foreign key (group_id) references group_security (id);

alter table users_group add constraint fk_users_group_users
foreign key (users_id) references users (id);
