version: "3.9"

services:
  hifood-db-dev:
    image: mysql:8.0.34
    profiles:
      - dev
    container_name: $DB_HOST
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "$DB_PORT:3306"
    networks:
      - hifood-network

  hifood-db-integration:
    image: postgres:16.0-alpine3.18
    profiles:
      - test
    container_name: $DB_HOST
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "$DB_PORT:5432"
    networks:
      - hifood-network

  hifood-api:
    image: hifood-api
    command: ["/wait-for-it.sh", "$DB_HOST:$DB_PORT", "-t", "60", "--", "java", "-jar", "/app/hifood-api.jar"]
    container_name: hifood-api
    ports:
      - "$SERVER_PORT:8080"
    environment:
      DB_HOST: $DB_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD      
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
    networks:
      - hifood-network
    depends_on:
      - $DB_SERVICE_CONTAINER

  hifood-integration-test:
    image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    profiles:
      - test    
    container_name: hifood-integration-test
    command:
      ["/bin/sh", "-c", "./wait-for-it.sh hifood-api:8080 -t 60 && npm install && npx cypress install && npm test"]
    environment:
      HOST_API: hifood-api
      SERVER_PORT: $SERVER_PORT
      DB_HOST: $DB_SERVICE_CONTAINER
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD      
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    networks:
      - hifood-network
    depends_on:
      - hifood-api

networks:
  hifood-network:
    driver: bridge
